address = "0.0.0.0:7777"
public_url = "http://127.0.0.1:7777"
#login_url = "https://login.netsblox.org"

# [admin]
# username = "admin"
# password = "somePassword"
# email = "admin@netsblox.org"

# [authorized_host]
# id = "LocalServices"
# url = "http://localhost:8080"
# secret = "SuperSecret"
# public = true

[database]
url = "mongodb://127.0.0.1:27017/"
name = "netsblox-rs"

[s3]
bucket = "netsbloxrs"
endpoint = "http://127.0.0.1:9000"
region_name = "us-east-1"  # default in minio

[s3.credentials]
access_key = "KEY"
secret_key = "MYSECRET"

[cookie]
name = "netsblox"
domain = "localhost"
key = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz0123456789ab"

[email]
sender = "NetsBlox <no-reply@netsblox.org>"

[email.smtp]
host = "smtp.gmail.com"
username = "USERNAME"
password = "PASSWORD"

[security]
allow_tor_login = false

[cache_settings]
num_projects = 500
num_users_membership_data = 1000
num_users_admin_data = 1000
num_users_friend_data = 1000
num_addresses = 1000