[package]
name = "netsblox_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.130", features = ["derive"] }
reqwest = {version = "0.11.9", features = ["json", "cookies"]}
netsblox_core = { path = "../core", version = "0.1.0" }
