[package]
name = "netsblox-api"
version = "0.5.0"
edition = "2021"
license = "MIT"
description = """
A client library for the NetsBlox cloud API
"""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.130", features = ["derive"] }
reqwest = {version = "0.11.9", features = ["json", "cookies"]}
futures-util = "0.3.19"
netsblox-api-common = { path = "../api-common", version = "0.5.0" }
tokio-tungstenite = {version = "0.16.1", features = ["native-tls"] }
tungstenite = "0.16.0"
tokio = "1.0.0"
derive_more = "0.99.17"
serde_json = "1.0.59"
